CREATE OR REPLACE FUNCTION GET_ACTUAL_AGE(WINNER_YEAR IN DATE) 
RETURN NUMBER 
IS AGE NUMBER;

BEGIN 
AGE := ((SYSDATE - WINNER_YEAR)/365.25);
RETURN AGE;
END;

SELECT W.FIRST_NAME, W.LAST_NAME, W.BIRTH_DATE, SYSDATE AS TODAY, GET_ACTUAL_AGE(W.BIRTH_DATE) AS EDAD
FROM ICEICEBABY.WINNER W;


CREATE OR REPLACE FUNCTION GET_AGE(WINNER_YEAR IN DATE, PRIZE_YEAR IN DATE) 
RETURN NUMBER 
IS AGE NUMBER;

BEGIN 
AGE := ((PRIZE_YEAR - WINNER_YEAR)/365.25);
RETURN AGE;
END;

SELECT W.FIRST_NAME, W.LAST_NAME, W.BIRTH_DATE, Y.YEAR_NAME, C.PRIZE_NAME, GET_AGE(W.BIRTH_DATE, Y.YEAR_NAME) AS EDAD
FROM ICEICEBABY.WINNER W
    INNER JOIN ICEICEBABY.PRIZE P ON P.WINNER_ID = W.WINNER_ID
    INNER JOIN ICEICEBABY.YEAR	Y ON P.YEAR_ID = Y.YEAR_ID
    INNER JOIN ICEICEBABY.CATEGORY C ON P.CATEGORY_ID = C.CATEGORY_ID;
    
CREATE OR REPLACE PROCEDURE ADD_WINNER
(WINNER_ID IN ICEICEBABY.PRIZE.WINNER_ID%TYPE,
 CATEGORY_ID IN ICEICEBABY.PRIZE.CATEGORY_ID%TYPE,
 RESIDENCE_ID IN ICEICEBABY.PRIZE.RESIDENCE_ID%TYPE,
 YEAR_ID IN ICEICEBABY.PRIZE.YEAR_ID%TYPE,
 ROLE_ID IN ICEICEBABY.PRIZE.ROLE_ID%TYPE,
 FIELD_ID IN ICEICEBABY.PRIZE.FIELD_ID%TYPE,
 MOTIVATION_ID IN ICEICEBABY.PRIZE.MOTIVATION_ID%TYPE)
IS
BEGIN
INSERT INTO ICEICEBABY.PRIZE(PRIZE_ID, WINNER_ID,CATEGORY_ID, RESIDENCE_ID, YEAR_ID, ROLE_ID, FIELD_ID, MOTIVATION_ID)VALUES(ICEICEBABY.PRIZE_SEQ.NEXTVAL, WINNER_ID,CATEGORY_ID, RESIDENCE_ID, YEAR_ID, ROLE_ID, FIELD_ID, MOTIVATION_ID);
COMMIT;
END;

SELECT * FROM ICEICEBABY.PRIZE ORDER BY PRIZE_ID DESC;
EXEC ADD_WINNER(5,2,25,8,10,16,3);
SELECT * FROM ICEICEBABY.PRIZE ORDER BY PRIZE_ID DESC;