CREATE OR REPLACE FUNCTION GET_ACTUAL_AGE(WINNER_YEAR IN DATE) 
RETURN NUMBER 
IS AGE NUMBER;

BEGIN 
AGE := ((SYSDATE - WINNER_YEAR)/365.25);
RETURN AGE;
END;

SELECT W.FIRST_NAME, W.LAST_NAME, W.BIRTH_DATE, SYSDATE AS TODAY, GET_ACTUAL_AGE(W.BIRTH_DATE) AS EDAD
FROM ICEICEBABY.WINNER W;


CREATE OR REPLACE FUNCTION GET_AGE(WINNER_YEAR IN DATE, PRIZE_YEAR IN DATE) 
RETURN NUMBER 
IS AGE NUMBER;

BEGIN 
AGE := ((PRIZE_YEAR - WINNER_YEAR)/365.25);
RETURN AGE;
END;

SELECT W.FIRST_NAME, W.LAST_NAME, W.BIRTH_DATE, Y.YEAR_NAME, C.PRIZE_NAME, GET_AGE(W.BIRTH_DATE, Y.YEAR_NAME) AS EDAD
FROM ICEICEBABY.WINNER W
    INNER JOIN ICEICEBABY.PRIZE P ON P.WINNER_ID = W.WINNER_ID
    INNER JOIN ICEICEBABY.YEAR	Y ON P.YEAR_ID = Y.YEAR_ID
    INNER JOIN ICEICEBABY.CATEGORY C ON P.CATEGORY_ID = C.CATEGORY_ID;