SELECT *
FROM (SELECT ROW_NUMBER () OVER (ORDER BY EXTRACT (YEAR FROM Y.YEAR_NAME) DESC) ORDEN, EXTRACT (YEAR FROM Y.YEAR_NAME) AS YEARS, W.FIRST_NAME, W.LAST_NAME, W.BIRTH_DATE, C.PRIZE_CATEGORY, C.PRIZE_NAME
    FROM ICEICEBABY.PRIZE P
        INNER JOIN ICEICEBABY.WINNER W
            ON P.WINNER_ID = W.WINNER_ID
        INNER JOIN ICEICEBABY.CATEGORY C
            ON P.CATEGORY_ID = C.CATEGORY_ID
        INNER JOIN ICEICEBABY.YEAR Y
            ON P.YEAR_ID = Y.YEAR_ID)
    WHERE ORDEN < 6;
    
SELECT *
FROM(SELECT ROW_NUMBER () OVER (ORDER BY EXTRACT (YEAR FROM Y.YEAR_NAME) DESC) ORDEN, EXTRACT (YEAR FROM Y.YEAR_NAME) AS YEARS, W.FIRST_NAME, W.LAST_NAME, W.BIRTH_DATE, C.PRIZE_CATEGORY, C.PRIZE_NAME
    FROM ICEICEBABY.PRIZE P
        INNER JOIN ICEICEBABY.WINNER W
            ON P.WINNER_ID = W.WINNER_ID
        INNER JOIN ICEICEBABY.CATEGORY C
            ON P.CATEGORY_ID = C.CATEGORY_ID
        INNER JOIN ICEICEBABY.YEAR Y
            ON P.YEAR_ID = Y.YEAR_ID) 
WHERE PRIZE_NAME LIKE 'The Nobel Prize in Physics'
GROUP BY FIRST_NAME, LAST_NAME, BIRTH_DATE, PRIZE_CATEGORY, PRIZE_NAME
HAVING COUNT(*) > 11;

SELECT COUNT (P.WINNER_ID) ORDEN, P.WINNER_ID, W.FIRST_NAME, W.LAST_NAME, W.BIRTH_DATE, C.PRIZE_CATEGORY, C.PRIZE_NAME
    FROM ICEICEBABY.PRIZE P
        INNER JOIN ICEICEBABY.WINNER W
            ON P.WINNER_ID = W.WINNER_ID
        INNER JOIN ICEICEBABY.CATEGORY C
            ON P.CATEGORY_ID = C.CATEGORY_ID
        INNER JOIN ICEICEBABY.YEAR Y
            ON P.YEAR_ID = Y.YEAR_ID
GROUP BY P.WINNER_ID, W.FIRST_NAME, W.LAST_NAME, W.BIRTH_DATE, C.PRIZE_CATEGORY, C.PRIZE_NAME
HAVING COUNT(P.WINNER_ID) > 1;

SELECT COUNT (P.FIELD_ID) ORDEN, P.WINNER_ID, W.FIRST_NAME, W.LAST_NAME, W.BIRTH_DATE, C.PRIZE_CATEGORY, C.PRIZE_NAME, F.FIELD_NAME
    FROM ICEICEBABY.PRIZE P
        INNER JOIN ICEICEBABY.WINNER W
            ON P.WINNER_ID = W.WINNER_ID
        INNER JOIN ICEICEBABY.CATEGORY C
            ON P.CATEGORY_ID = C.CATEGORY_ID
        INNER JOIN ICEICEBABY.YEAR Y
            ON P.YEAR_ID = Y.YEAR_ID
        INNER JOIN ICEICEBABY.FIELD F
            ON P.FIELD_ID = F.FIELD_ID
GROUP BY P.WINNER_ID, W.FIRST_NAME, W.LAST_NAME, W.BIRTH_DATE, C.PRIZE_CATEGORY, C.PRIZE_NAME, F.FIELD_NAME
HAVING COUNT(*) = (SELECT MAX(COUNT(*)) FROM ICEICEBABY.FIELD GROUP BY FIELD_ID); 

SELECT COUNT (P.CATEGORY_ID) ORDEN, C.*
    FROM ICEICEBABY.PRIZE P
        INNER JOIN ICEICEBABY.CATEGORY C
            ON P.CATEGORY_ID = C.CATEGORY_ID
GROUP BY P.CATEGORY_ID, C.CATEGORY_ID, C.PRIZE_NAME, C.PRIZE_CATEGORY
HAVING COUNT(*) = (SELECT MIN(COUNT(*)) FROM ICEICEBABY.PRIZE GROUP BY CATEGORY_ID);

--SE HARA CON RESIDENCIA 
SELECT COUNT (P.RESIDENCE_ID) ORDEN, P.WINNER_ID, W.FIRST_NAME, W.LAST_NAME, W.BIRTH_DATE, C.PRIZE_CATEGORY, C.PRIZE_NAME, CO.COUNTRY_NAME 
    FROM ICEICEBABY.PRIZE P
        INNER JOIN ICEICEBABY.WINNER W
            ON P.WINNER_ID = W.WINNER_ID
        INNER JOIN ICEICEBABY.CATEGORY C
            ON P.CATEGORY_ID = C.CATEGORY_ID
        INNER JOIN ICEICEBABY.YEAR Y
            ON P.YEAR_ID = Y.YEAR_ID
        INNER JOIN ICEICEBABY.COUNTRY CO
            ON P.RESIDENCE_ID = CO.COUNTRY_ID
GROUP BY P.WINNER_ID, W.FIRST_NAME, W.LAST_NAME, W.BIRTH_DATE, C.PRIZE_CATEGORY, C.PRIZE_NAME, CO.COUNTRY_NAME
HAVING COUNT(*) = (SELECT MAX(COUNT(*)) FROM ICEICEBABY.PRIZE GROUP BY RESIDENCE_ID);