CREATE TABLE ICEICEBABY.WINNER
(
  WINNER_ID         NUMBER                           NOT NULL,
  FIRST_NAME        VARCHAR2(100),
  LAST_NAME         VARCHAR2(100),
  BIRTH_DATE        DATE,
  COUNTRY_ID        NUMBER
);

ALTER TABLE ICEICEBABY.WINNER ADD (
  CONSTRAINT WINNER_PK
  PRIMARY KEY
  (WINNER_ID)
  ENABLE VALIDATE);
  


CREATE TABLE ICEICEBABY.COUNTRY
(
  COUNTRY_ID         NUMBER                           NOT NULL,
  COUNTRY_NAME       VARCHAR2(100)
);

ALTER TABLE ICEICEBABY.COUNTRY ADD (
  CONSTRAINT COUNTRY_PK
  PRIMARY KEY
  (COUNTRY_ID)
  ENABLE VALIDATE);
  
  
  
CREATE TABLE ICEICEBABY.PRIZE
(
  PRIZE_ID         NUMBER                           NOT NULL,
  WINNER_ID        NUMBER,
  CATEGORY_ID      NUMBER,
  RESIDENCE_ID     NUMBER,
  YEAR_ID          NUMBER,
  ROLE_ID          NUMBER,
  FIELD_ID         NUMBER,
  MOTIVATION_ID    NUMBER
);

ALTER TABLE ICEICEBABY.PRIZE ADD (
  CONSTRAINT PRIZE_PK
  PRIMARY KEY
  (PRIZE_ID)
  ENABLE VALIDATE);
  
  
CREATE TABLE ICEICEBABY.CATEGORY
(
 CATEGORY_ID      NUMBER                           NOT NULL,
 PRIZE_CATEGORY   VARCHAR2(100),
 PRIZE_NAME       VARCHAR2(100)
);

ALTER TABLE ICEICEBABY.CATEGORY ADD (
  CONSTRAINT CATEGORY_PK
  PRIMARY KEY
  (CATEGORY_ID)
  ENABLE VALIDATE);


CREATE TABLE ICEICEBABY.YEAR
(
  YEAR_ID         NUMBER                           NOT NULL,
  YEAR_NAME       DATE
);

ALTER TABLE ICEICEBABY.YEAR ADD (
  CONSTRAINT YEAR_PK
  PRIMARY KEY
  (YEAR_ID)
  ENABLE VALIDATE);
  
CREATE TABLE ICEICEBABY.ROLE
(
  ROLE_ID         NUMBER                           NOT NULL,
  ROLE_NAME       VARCHAR2(200),
  COUNTRY_ID      NUMBER
);

ALTER TABLE ICEICEBABY.ROLE ADD (
  CONSTRAINT ROLE_PK
  PRIMARY KEY
  (ROLE_ID)
  ENABLE VALIDATE);
  

CREATE TABLE ICEICEBABY.FIELD
(
  FIELD_ID         NUMBER                           NOT NULL,
  FIELD_NAME       VARCHAR2(100)
);

ALTER TABLE ICEICEBABY.FIELD ADD (
  CONSTRAINT FIELD_PK
  PRIMARY KEY
  (FIELD_ID)
  ENABLE VALIDATE);
  

CREATE TABLE ICEICEBABY.MOTIVATION
(
  MOTIVATION_ID         NUMBER                           NOT NULL,
  MOTIVATION_NAME       VARCHAR2(255)
);

ALTER TABLE ICEICEBABY.MOTIVATION ADD (
  CONSTRAINT MOTIVATION_PK
  PRIMARY KEY
  (MOTIVATION_ID)
  ENABLE VALIDATE);
  
ALTER TABLE ICEICEBABY.WINNER ADD 
CONSTRAINT WINNER_R01
 FOREIGN KEY (COUNTRY_ID)
 REFERENCES ICEICEBABY.COUNTRY (COUNTRY_ID)
 ENABLE
 VALIDATE;
 
ALTER TABLE ICEICEBABY.PRIZE ADD 
CONSTRAINT PRIZE_R01
 FOREIGN KEY (WINNER_ID)
 REFERENCES ICEICEBABY.WINNER (WINNER_ID)
 ENABLE
 VALIDATE;
 
ALTER TABLE ICEICEBABY.PRIZE ADD 
CONSTRAINT PRIZE_R02
 FOREIGN KEY (CATEGORY_ID)
 REFERENCES ICEICEBABY.CATEGORY (CATEGORY_ID)
 ENABLE
 VALIDATE;
 
ALTER TABLE ICEICEBABY.PRIZE ADD 
CONSTRAINT PRIZE_R03
 FOREIGN KEY (RESIDENCE_ID)
 REFERENCES ICEICEBABY.COUNTRY (COUNTRY_ID)
 ENABLE
 VALIDATE;
 
ALTER TABLE ICEICEBABY.PRIZE ADD 
CONSTRAINT PRIZE_R04
 FOREIGN KEY (YEAR_ID)
 REFERENCES ICEICEBABY.YEAR (YEAR_ID)
 ENABLE
 VALIDATE;
 
ALTER TABLE ICEICEBABY.PRIZE ADD 
CONSTRAINT PRIZE_R05
 FOREIGN KEY (ROLE_ID)
 REFERENCES ICEICEBABY.ROLE (ROLE_ID)
 ENABLE
 VALIDATE;
 
ALTER TABLE ICEICEBABY.PRIZE ADD 
CONSTRAINT PRIZE_R06
 FOREIGN KEY (FIELD_ID)
 REFERENCES ICEICEBABY.FIELD (FIELD_ID)
 ENABLE
 VALIDATE;
 
ALTER TABLE ICEICEBABY.PRIZE ADD 
CONSTRAINT PRIZE_R07
 FOREIGN KEY (MOTIVATION_ID)
 REFERENCES ICEICEBABY.MOTIVATION (MOTIVATION_ID)
 ENABLE
 VALIDATE;
 

ALTER TABLE ICEICEBABY.ROLE ADD 
CONSTRAINT ROLE_R01
 FOREIGN KEY (COUNTRY_ID)
 REFERENCES ICEICEBABY.COUNTRY (COUNTRY_ID)
 ENABLE
 VALIDATE;
 
CREATE SEQUENCE ICEICEBABY.WINNER_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 0
NOCACHE 
NOCYCLE 
NOORDER;

CREATE SEQUENCE ICEICEBABY.COUNTRY_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 0
NOCACHE 
NOCYCLE 
NOORDER;

CREATE SEQUENCE ICEICEBABY.PRIZE_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 0
NOCACHE 
NOCYCLE 
NOORDER;

CREATE SEQUENCE ICEICEBABY.YEAR_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 0
NOCACHE 
NOCYCLE 
NOORDER;

CREATE SEQUENCE ICEICEBABY.ROLE_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 0
NOCACHE 
NOCYCLE 
NOORDER;

CREATE SEQUENCE ICEICEBABY.FIELD_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 0
NOCACHE 
NOCYCLE 
NOORDER;

CREATE SEQUENCE ICEICEBABY.MOTIVATION_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 0
NOCACHE 
NOCYCLE 
NOORDER;

CREATE SEQUENCE ICEICEBABY.CATEGORY_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 0
NOCACHE 
NOCYCLE 
NOORDER;